### ISSUE TITLE
Yarn or NPM?

### ISSUE THREAD

**Issue by jhsu802701** [FoodIsLifeBGP/banana-admin#17]
This app has the package-lock.json and yarn.lock files.  The yarn.lock file was recently introduced, but the setup instructions specify the use of NPM.  Is there a plan to migrate from NPM to Yarn?

**Comment by tackc** [comment]
After playing around a bit, it seems like Storybook is preferring Yarn and causing it to install. I'm looking at some package upgrades as well and working to fix some breaking changes

**Comment by tackc** [comment]
Issue fixed with #21 - Project Cleanup. We are now using yarn
